### ISSUE TITLE
Update to .Net 5

### ISSUE THREAD

**Issue by Skull-Lee** [siemens/sourcegrid#3]
Though I could install the NuGet package in a c# .Net5 project, if I check the source out, it cannot be translated to .Net5 as is.

I can't find another repo of SourceGrid, so I plan to update this to .Net5 so that I can update my solution that uses Source Grid 2 to a .Net5 solution.

**Comment by huanlin** [comment]
In my fork, I've upgraded this project to support .NET 6.
If you're interested, check this out: https://github.com/huanlin/SourceGrid
