### ISSUE TITLE
NuGet package not found

### ISSUE THREAD

**Issue by bitwizardry** [siemens/sourcegrid#30]
Hello friends,

I just tried to install the package from the command line and got this error: NU1101 (package not found)

Am I missing something from the command line? 
dotnet add package siemens.sourcegrid --version 3.0.0

I'm using the latest version of VS -17.9.0 Preview 5.0, .NET 8.0 project

**Comment by cuppm** [comment]
I don't see it published to NuGet when I do a browse search, just these:
![image](https://github.com/siemens/sourcegrid/assets/1964795/e8356e7c-01b9-411f-a542-d5ca1bd6f310)

I downloaded the code and built it locally and/or just include the project in my solution.

**Comment by Rj-Rahul-96** [comment]
Based on an internal discussion we have decided to release SourceGrid V2.0.0 and V3.0.0 in our GitHub repository.
SourceGrid nuget package can be used in visual studio by configuring Github as nuget source.
Nuget source Link for configuring in visual studio : [SourceGrid](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnuget.pkg.github.com%2FSiemens%2Findex.json&data=05%7C02%7Crahul.rajesh%40siemens.com%7C529a017e2d01450cf71b08dc3c597754%7C38ae3bcd95794fd4addab42e1495d55a%7C1%7C0%7C638451602179875886%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=YvpNUOj1pKlJpoT5QBollCpgcXNW0b%2BsN13Ep5zQe48%3D&reserved=0)
