### ISSUE TITLE
Suggestion: Add the Demo/Sample Projects

### ISSUE THREAD

**Issue by cuppm** [siemens/sourcegrid#31]
Should the demo/sample projects be added to the repository as well?  I've been looking at examples old CodePlex 4.4.0 version of the project to "see how things are done."  But it would be helpful to newer users to have it in the same location as the current version of the library and know that it's the most recent version of the examples.  Especially since the CodePlex code is no longer publicly available.

**Comment by cuppm** [comment]
Additionally there are several references to a UIGrid project and UIGridCell by @sandhraprakash in comments that necessitated several code changes and enhancements.  I'm guessing that is a Siemens project that is using SourceGrid?  Would it be possible to examples or descriptions of how the improvements are used to see if they are applicable to others?

**Comment by Rj-Rahul-96** [comment]
Based on the internal discussion it is not feasible now to add sample project for all the previous changes, moving forward we can include sample project for improvements or features. At present we have only this sample project. [Src/WindowsFormsSample](https://github.com/siemens/sourcegrid/tree/master/Src/WindowsFormsSample).

**Comment by cuppm** [comment]
Thanks for pointing that project out.  Not sure how I missed it.  😳  I think I was used to it being included in the same solution as the main library one.
