### ISSUE TITLE
DataGrid - No Column Headers

### ISSUE THREAD

**Issue by cuppm** [siemens/sourcegrid#32]
I was following the sample 29 from the CodePlex 4.4.0 version to see how to use the `DataGrid` control, but the current version of the library does not display the column headers.  I think it has something to do with the change to the `DataGrid.GetCell(int p_iRow, int p_iCol)` function.

Previous version of the function:
```c#
public override Cells.ICellVirtual GetCell(int p_iRow, int p_iCol)
{
	if (mBoundList == null)
		return null;
	if (p_iCol >= Columns.Count)
		return null;
			
	if (p_iRow < FixedRows)
		return Columns[p_iCol].HeaderCell;
	else
		return Columns[p_iCol].GetDataCell(p_iRow);
}
```

Current version of the function: 
```c#
public override Cells.ICellVirtual GetCell(int p_iRow, int p_iCol)
{
	if (mBoundList == null)
		return null;
	if (p_iCol >= Columns.Count)
		return null;

    //sandhra.prakash@siemens.com: changed fixedRows to headerRowCount for FreezePanes enhancement.
    if (p_iRow < HeaderRowCount)
    {
        if (p_iRow <= 0)
        {
            return Columns[p_iCol].HeaderCell;
        }
        else
        {
            //Sandhra.prakash@siemens.com: To Support Filter cell.
            return Columns[p_iCol].FilterCell;
        }
    }
    else
    {
        return Columns[p_iCol].GetDataCell(p_iRow);
    }
}
```

It appears that the `GridVirtual.HeaderRowCount` that is being checked is always `0` as it is protected and has no calls that set it (from a Visual Studio find references check).  So it can never enter the block that returns the column header cell.  I tried changing the if condition to be `if (p_iRow <= HeaderRowCount)` but that displays the column headers instead of the first data row.

Since I'm unsure of intent of the code change, I'm not sure where else to look to make a suggested fix.

**Comment by cuppm** [comment]
It appears you must be setting `GridVirtual.HeaderRowCount` in your unpublished extensions for the FreezePanes enhancement?  Can you please provide details on how you use it?  If I add `HeaderRowCount = 1;` to the constructor of `DataGrid` it appears to solve the issue, but whether that is the correct fix is unclear without details of the intent of that property.

**Comment by Rj-Rahul-96** [comment]
```HeaderRowCount``` need to be set based on the requirement . If requirement is only header row then ```HeaderRowCount = 1``` is the right approach and if requirement is header and filter rows then you need to set ```HeaderRowCount = 2```

**Comment by cuppm** [comment]
I don't think you should mark this as complete as your current version does not address the issue with the control (unless I missed a code change commit).  The `GridVirtual.HeaderRowCount` property is never set, is currently marked as `protected`, and the `public` control `DataGrid` also never changes that value.  That means the current implementation as published in the library does not work without the user deriving their own class from `DataGrid` as there is no other way of changing the `GridVirtual.HeaderRowCount` value.

Note that `frmSample43` from the WindowsFormsSamples project currently displays without column headers:
![image](https://github.com/siemens/sourcegrid/assets/1964795/8d5ce5da-aa4c-4e1b-b160-5755717344c3)
