### ISSUE TITLE
Package  siemens.sourcegrid doesn't exist on nuget.org

### ISSUE THREAD

**Issue by zabanet** [siemens/sourcegrid#34]
According to information on project github page there should be nuget package named  siemens.sourcegrid, but there's no such a thing in official nuget repository. Do I have to add some custom repositiory for this? Couldn't find information on this topic.

**Comment by Rj-Rahul-96** [comment]
Based on an internal discussion we have decided to release SourceGrid V2.0.0 and V3.0.0 in our GitHub repository.
SourceGrid nuget package can be used in visual studio by configuring Github as nuget source.
Nuget source Link for configuring in visual studio : [SourceGrid](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnuget.pkg.github.com%2FSiemens%2Findex.json&data=05%7C02%7Crahul.rajesh%40siemens.com%7C529a017e2d01450cf71b08dc3c597754%7C38ae3bcd95794fd4addab42e1495d55a%7C1%7C0%7C638451602179875886%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=YvpNUOj1pKlJpoT5QBollCpgcXNW0b%2BsN13Ep5zQe48%3D&reserved=0)

**Comment by zabanet** [comment]
Thank you!
