### ISSUE TITLE
Add Tree view style view to Source Grid

### ISSUE THREAD

**Issue by vimal-pushkaran** [siemens/sourcegrid#40]
Hi Team,
Many custom Datagrids have a feature of displaying the items based on some hierarchical order, in the form a treeview as the first column. Basically, it arranges the child nodes based on the relation and user should be able to expand / collapse the nodes. 

Is there any option to add this feature to SourceGrid ? If not, please provide some pointers to start of with.

Regards,
Vimal

**Comment by Rj-Rahul-96** [comment]
Hi @vimal-pushkaran ,
SourceGrid does not support any form of hierarchy view like tree view.
Based on the internal discussion, it is not a feasible option to add this feature to SourceGrid.

Regards,
Rahul
