### ISSUE TITLE
Mouse Drag Selection Not Working by Default

### ISSUE THREAD

**Issue by cuppm** [siemens/sourcegrid#8]
The changes in the Siemens update caused the default behavior of mouse drag to not update the grid cell selection any more.  With the last CodePlex version (4.40) you could click in a cell and drag the cursor to select multiple cells - like the way Excel functions for selecting multiple cells.  In the current version the cell that gets the initial mouse down is selected but no additional cells are added to the selection when dragging.

Is there a setting somewhere that should be set for this to work like before?

**Comment by cuppm** [comment]
Drag selection appears to have been changed to off by default.  You enable it with:
```c#
mySourceGridControl.Selection.EnableDragSelection = true;
```

**Comment by Rj-Rahul-96** [comment]
Closing issue as it is related to configuration/setting.
